version: '3'

# grafana 10.0.1
#
services:
  grafana:
    image: grafana/grafana:10.0.1
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '1000'
    ports:
      - '3000:3000'
    volumes:
      - './volumes/grafana/var/lib/grafana:/var/lib/grafana'

